server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
      - id: address-service
        uri: lb://address-service
        predicates:
        - Path=/address/**
      - id: order-details-processor
        uri: lb://order-details-processor
        predicates:
        - Path=/order-details/**
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
      - id: aggregator-service
        uri: lb://aggregator-service
        predicates:
        - Path=/aggregate/**
      - id: event-details-fetcher
        uri: lb://event-details-fetcher
        predicates:
        - Path=/event-details/**
