server:
  port: 80

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
      - id: address-service
        uri: lb://address-service