server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
      - id: address-service
        uri: lb://address-service
        predicates:
        - Path=/address/**
      - id: address-service
        uri: lb://order-details-processor
        predicates:
        - Path=/order-details/**
